// <auto-generated />
using BTJQ.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BTJQ.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20191118063512_i")]
    partial class i
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BTJQ.Models.EmployeeCreateModel", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.Property<int>("SkillID");

                    b.Property<int>("YearsExperience");

                    b.HasKey("EmployeeID");

                    b.ToTable("EmployeeCreateModel");
                });

            modelBuilder.Entity("BTJQ.Models.EmployeeEditModel", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmployeeName");

                    b.Property<string>("PhoneNumber");

                    b.Property<int>("SkillID");

                    b.Property<int>("YearsExperience");

                    b.HasKey("EmployeeID");

                    b.ToTable("EmployeeEditModel");
                });

            modelBuilder.Entity("BTJQ.Models.EmployeeViewModel", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmployeeName");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("Skill");

                    b.Property<int>("YearsExperience");

                    b.HasKey("EmployeeID");

                    b.ToTable("EmployeeViewModel");
                });

            modelBuilder.Entity("BTJQ.Models.tblEmployee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmployeeName");

                    b.Property<string>("PhoneNumber");

                    b.Property<int>("SkillID");

                    b.Property<int>("YearsExperience");

                    b.HasKey("EmployeeID");

                    b.ToTable("tblEmployees");
                });

            modelBuilder.Entity("BTJQ.Models.tblSkill", b =>
                {
                    b.Property<int>("SkillID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title");

                    b.HasKey("SkillID");

                    b.ToTable("tblSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
